version: "3.7"

services:
  postgres-shorts:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=shorts
      - POSTGRES_PASSWORD=notsecureatall
      - POSTGRES_DB=shorts
    networks:
      - intranet

  shorts:
    build:
      context: .
    env_file: .env
    ports:
      - 8080:8090

    networks:
      - intranet

networks:
  intranet:
