version: "3.7"

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    networks:
      - intranet
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oathkeeper.rule=Host(`oathkeeper`)"
      - "traefik.http.routers.oathkeeper.entrypoints=web"
      - "traefik.http.routers.oathkeeper.service=oathkeeper"
      - "traefik.http.services.oathkeeper.loadbalancer.server.port=4456"
      - "traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions"
      - "traefik.http.middlewares.oathkeeper.forwardauth.authResponseHeaders=X-User"

  hello:
    build:
      context: "hello"
    networks:
      - intranet
    labels:
      - "traefik.enable=true"
      # App settings
      - "traefik.http.routers.hello.rule=Path(`/hello`)"
      - "traefik.http.routers.hello.entrypoints=web"
      # Attach to the oathkeeper middleware defined in oathkeeper
      - "traefik.http.routers.hello.service=hello"
      - "traefik.http.services.hello.loadbalancer.server.port=8090"
      - "traefik.http.routers.hello.middlewares=oathkeeper@docker"

  postgres-kratos:
    extends:
      file: ../../_common/docker-compose.yml
      service: postgres-kratos

  kratos-migrate:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos-migrate

  kratos:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos

  kratos-selfservice-ui-node:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos-selfservice-ui-node

  mailslurper:
    extends:
      file: ../../_common/docker-compose.yml
      service: mailslurper

networks:
  intranet:
