services:
  kong:
    image: kong:3.9
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/kong.yaml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    volumes:
      - ./config/kong.yaml:/kong/kong.yaml:ro
    depends_on:
      - oathkeeper
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v26.2.0
    depends_on:
      - kratos
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  hello:
    build:
      context: "../_common/hello"
    networks:
      - intranet

  world:
    build:
      context: "../_common/hello"
    networks:
      - intranet

  postgres-kratos:
    extends:
      file: ../_common/docker-compose.yml
      service: postgres-kratos

  kratos-migrate:
    extends:
      file: ../_common/docker-compose.yml
      service: kratos-migrate
    depends_on:
      postgres-kratos:
        condition: service_healthy

  kratos:
    extends:
      file: ../_common/docker-compose.yml
      service: kratos
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully

  kratos-selfservice-ui-node:
    extends:
      file: ../_common/docker-compose.yml
      service: kratos-selfservice-ui-node

  mailpit:
    extends:
      file: ../_common/docker-compose.yml
      service: mailpit

networks:
  intranet:
