services:
  flask:
    build:
      context: .
    environment:
      - FLASK_APP=autoapp.py
      - KRATOS_EXTERNAL_API_URL=http://kratos:4433
      - KRATOS_UI_URL=http://127.0.0.1:4455
      - KETO_API_READ_URL=http://keto:4466
    depends_on:
      - kratos
      - keto
    ports:
      - "5001:5001"
    networks:
      - intranet

  keto:
    image: oryd/keto:v26.2.0
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    volumes:
      - ./keto:/home/ory
    ports:
      - "4466:4466"
      - "4467:4467"
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v26.2.0
    depends_on:
      - kratos
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    ports:
      - "8080:4455"
      - "4456:4456"
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  postgres-kratos:
    extends:
      file: ../_common/docker-compose.yml
      service: postgres-kratos

  kratos-migrate:
    extends:
      file: ../_common/docker-compose.yml
      service: kratos-migrate
    depends_on:
      postgres-kratos:
        condition: service_healthy

  kratos:
    extends:
      file: ../_common/docker-compose.yml
      service: kratos
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully

  kratos-selfservice-ui-node:
    extends:
      file: ../_common/docker-compose.yml
      service: kratos-selfservice-ui-node

  mailpit:
    extends:
      file: ../_common/docker-compose.yml
      service: mailpit

networks:
  intranet:
