services:
  nginx:
    image: nginx:1.29-alpine
    ports:
      - "8080:80"
    depends_on:
      - oathkeeper
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v26.2.0
    depends_on:
      - kratos
    ports:
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  hello:
    build:
      context: "../../_common/hello"
    networks:
      - intranet

  hydrator:
    build:
      context: "../../_common/hydrator"
    networks:
      - intranet

  postgres-kratos:
    extends:
      file: ../../_common/docker-compose.yml
      service: postgres-kratos

  kratos-migrate:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos-migrate
    depends_on:
      postgres-kratos:
        condition: service_healthy

  kratos:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully

  kratos-selfservice-ui-node:
    extends:
      file: ../../_common/docker-compose.yml
      service: kratos-selfservice-ui-node

  mailpit:
    extends:
      file: ../../_common/docker-compose.yml
      service: mailpit

networks:
  intranet:
