name: django-ory-cloud

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test-playwright:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Run Playwright tests
        working-directory: ./django-ory-cloud
        run: npm i && npx playwright install --with-deps && make test
