name: dotnet-ory-network

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test-playwright:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Run Playwright tests
        working-directory: ./dotnet-ory-network
        run: make test
